apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-data-pvc
  namespace: cisnux-skywalker-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi